---
title: "Slides for SZT prez"
author: "János Poór"
date: "`r Sys.Date()`"
output: rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE, warning=FALSE}
library(here)
library(dplyr)
library(ggplot2)
library(lubridate)
library(scales)
library(tidyr)
library(ggrepel)
library(stringr)
library(RColorBrewer)
```

```{r, message=FALSE, include=FALSE}
#########################################################################################
# Data Extraction #######################################################################
#########################################################################################

# Set JAVA_HOME, set max. memory, and load rJava library
Sys.setenv(JAVA_HOME = "C:\\Program Files\\Java\\jre1.8.0_171")
options(java.parameters = "-Xmx2g")
library(rJava)

# Output Java version
.jinit()
print(.jcall("java/lang/System", "S", "getProperty", "java.version"))

# Load RJDBC library
library(RJDBC)

# Get credentials
datamnr <-
  config::get("datamnr", file = "C:\\Users\\PoorJ\\Projects\\config.yml")

# Create connection driver
jdbcDriver <-
  JDBC(driverClass = "oracle.jdbc.OracleDriver", classPath = "C:\\Users\\PoorJ\\Desktop\\ojdbc7.jar")

# Open connection: kontakt---------------------------------------------------------------
jdbcConnection <-
  dbConnect(
    jdbcDriver,
    url = datamnr$server,
    user = datamnr$uid,
    password = datamnr$pwd
  )

# Fetch data
t_call_times <- dbGetQuery(jdbcConnection, 'select * from t_call_times_2018_cor UNION select * from t_call_times_2019_cor')
t_mnap <- dbGetQuery(jdbcConnection, 'select * from t_mnap')

# Close db connection: kontakt
dbDisconnect(jdbcConnection)


# Transformations
t_call_times <- t_call_times %>%
  mutate(EVENT_END = ymd_hms(EVENT_END)) %>%
  #filter(EVENT_END < as.Date("2019-01-01")) %>%
  replace_na(list(PRODUCT_LINE = "UNKNOWN", PRODUCT_CODE = "UNKNOWN", CASE_TYPE_EN = "UNKNOWN"))

t_call_times[t_call_times$CASE_TYPE_EN == "Delete contract", "CASE_TYPE_EN"] <- "Contract termination"

t_call_times[ t_call_times$ACTIVITY_EN == "!Delete contract", "ACTIVITY_EN"] <- "Delete contract"

t_call_times[t_call_times$CASE_TYPE_EN == "Claim report" &
  t_call_times$ACTIVITY_EN %in% c("Provide information Property assignments", "Provide information Motor vehicle claim report") &
  startsWith(t_call_times$CASE_ID, "S"), "ACTIVITY_EN"] <- "Provide information NOT on claim file"

t_call_times[t_call_times$CASE_TYPE_EN == "Claim report" &
  t_call_times$ACTIVITY_EN %in% c("Provide information Property assignments", "Provide information Motor vehicle claim report") &
  startsWith(t_call_times$CASE_ID, "K"), "ACTIVITY_EN"] <- "Provide information on claim file"

t_call_times[t_call_times$ACTIVITY_EN %in%
               c("Request claim recording", "Claim report (request inspection)"), "ACTIVITY_EN"] <- "Report claim"

t_call_times[t_call_times$CASE_TYPE_EN == "Claim report", "CASE_TYPE_EN"] <- "Claims"

t_call_times[t_call_times$CASE_TYPE_EN == "Provide information" & 
               t_call_times$ACTIVITY_EN == "Provide information Premium settlement", "CASE_TYPE_EN"] <- "Premium"

t_call_times[t_call_times$CASE_TYPE_EN == "Premium handling", "CASE_TYPE_EN"] <- "Premium"

t_call_times[t_call_times$CASE_TYPE_EN == "Provide information" & 
               t_call_times$ACTIVITY_EN != "Provide information Premium settlement", "CASE_TYPE_EN"] <- "General info"

t_mnap <- t_mnap %>% mutate(IDOSZAK = ymd_hms(IDOSZAK))
```


# 2. FTE Impact Map


```{r, include = TRUE, fig.width=10}
t_call_times %>%
  # Transform data
  filter(PRODUCT_LINE != "UNKNOWN") %>% 
  filter(
    (EVENT_END >= as.Date('2018-01-01') & EVENT_END < as.Date('2018-06-01')) |
    (EVENT_END >= as.Date('2019-01-01') & EVENT_END < as.Date('2019-06-01'))
         ) %>%
  mutate(YEAR = paste("Jan-May", lubridate::year(EVENT_END))) %>% 
  mutate(EVENT_MONTH = floor_date(EVENT_END, unit = "month"),
         #CASE_TYPE_EN = forcats::fct_lump(factor(CASE_TYPE_EN), n = 7),
         SEGMENT = forcats::fct_lump(paste(CASE_TYPE_EN, PRODUCT_LINE), n = 9, other_level = "Everything else")) %>%
  group_by(YEAR, EVENT_MONTH,  SEGMENT) %>%
  summarize(CALL_VOLUME = n(),
            CALL_TIME_SEC = sum(CALL_TIME)) %>%
  ungroup() %>%
  left_join(t_mnap, by = c("EVENT_MONTH" = "IDOSZAK")) %>% 
  mutate(FTE = CALL_TIME_SEC/60/60/6.5/MNAP,
         COST = FTE/CALL_VOLUME*1000) %>%
  # Compute monthly averages
  group_by(YEAR, SEGMENT) %>% 
  summarize(
            CALL_VOLUME = mean(CALL_VOLUME),
            FTE = mean(FTE),
            COST = mean(COST)) %>%
  filter(SEGMENT != "Everything else") %>% 
  arrange(YEAR, desc(FTE)) %>% 
  # Plot
  ggplot(aes(x = CALL_VOLUME, y = COST, label = SEGMENT)) +
    geom_point(aes(size = FTE), colour = "blue") +
    geom_label_repel(aes(label = SEGMENT),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50',
                  force = 50,
                  size = 3.5) +
    facet_grid(.~YEAR) +
    coord_cartesian(ylim = c(0.6, 1)) +
    labs(
      x = "Calls (Monthly Average)",
    y = "Cost per Call (Normalized FTE)",
    title = "Impact Map of Processes"
    )
```


```{r, include = TRUE, fig.height=6, fig.width=7}
t_call_times %>%
  # Transform data
  filter(PRODUCT_LINE != "UNKNOWN") %>% 
  filter(
    #(EVENT_END >= as.Date('2018-01-01') & EVENT_END < as.Date('2018-06-01')) |
    EVENT_END >= as.Date('2019-01-01') & EVENT_END < as.Date('2019-06-01')
         ) %>%
  mutate(YEAR = paste("Jan-May", lubridate::year(EVENT_END))) %>% 
  mutate(EVENT_MONTH = floor_date(EVENT_END, unit = "month"),
         #CASE_TYPE_EN = forcats::fct_lump(factor(CASE_TYPE_EN), n = 7),
         SEGMENT = forcats::fct_lump(paste(CASE_TYPE_EN, PRODUCT_LINE), n = 9, other_level = "Everything else")) %>%
  group_by(YEAR, EVENT_MONTH,  SEGMENT) %>%
  summarize(CALL_VOLUME = n(),
            CALL_TIME_MEAN = mean(CALL_TIME),
            CALL_TIME_SEC = sum(CALL_TIME)) %>%
  ungroup() %>%
  left_join(t_mnap, by = c("EVENT_MONTH" = "IDOSZAK")) %>% 
  mutate(FTE = CALL_TIME_SEC/60/60/6.5/MNAP,
         COST = FTE/CALL_VOLUME*1000) %>%
  # Compute monthly averages
  group_by(YEAR, SEGMENT) %>% 
  summarize(
            CALL_VOLUME = mean(CALL_VOLUME),
            FTE = mean(FTE),
            CALL_TIME_MEAN = mean(CALL_TIME_MEAN),
            COST = mean(COST)) %>%
  filter(SEGMENT != "Everything else") %>% 
  arrange(YEAR, desc(FTE)) %>% 
  # Plot
  ggplot(aes(x = CALL_VOLUME, y = CALL_TIME_MEAN, label = SEGMENT)) +
    geom_point(aes(size = FTE), colour = "slateblue") +
    geom_label_repel(aes(label = SEGMENT),
                  box.padding   = 0.55, 
                  point.padding = 0.5,
                  segment.color = 'grey50',
                  force = 50,
                  size = 3.5) +
    #facet_grid(.~YEAR) +
    #coord_cartesian(ylim = c(0.6, 1)) +
    labs(
      x = "Calls per Month",
    y = "Call Time (Sec)",
    title = "Impact Map of Processes",
    subtitle = "Which Processes Consume Most Resources",
    caption = "Measurement period: Jan-May, 2019"
    )
```


```{r, include = TRUE, fig.height=6.5, fig.width=8}
t_call_times %>%
  # Transform data
  filter(PRODUCT_LINE != "UNKNOWN") %>%
  filter(
    # (EVENT_END >= as.Date('2018-01-01') & EVENT_END < as.Date('2018-06-01')) |
    EVENT_END >= as.Date("2019-01-01") & EVENT_END < as.Date("2019-06-01")
  ) %>%
  mutate(YEAR = paste("Jan-May", lubridate::year(EVENT_END))) %>%
  mutate(
    EVENT_MONTH = floor_date(EVENT_END, unit = "month"),
    # CASE_TYPE_EN = forcats::fct_lump(factor(CASE_TYPE_EN), n = 7),
    SEGMENT = forcats::fct_lump(paste(CASE_TYPE_EN, PRODUCT_LINE), n = 10, other_level = "Everything else")
  ) %>%
  group_by(YEAR, EVENT_MONTH, SEGMENT) %>%
  summarize(
    CALL_VOLUME = n(),
    CALL_TIME_MEAN = mean(CALL_TIME),
    CALL_TIME_SEC = sum(CALL_TIME)
  ) %>%
  ungroup() %>%
  left_join(t_mnap, by = c("EVENT_MONTH" = "IDOSZAK")) %>%
  mutate(
    FTE = CALL_TIME_SEC / 60 / 60 / 6.5 / MNAP,
    COST = FTE / CALL_VOLUME * 1000
  ) %>%
  # Compute monthly averages
  group_by(YEAR, SEGMENT) %>%
  summarize(
    CALL_VOLUME = mean(CALL_VOLUME),
    FTE = mean(FTE),
    CALL_TIME_MEAN = mean(CALL_TIME_MEAN),
    COST = mean(COST)
  ) %>%
  filter(SEGMENT != "Everything else") %>%
  arrange(YEAR, desc(FTE)) %>%
  # Plot
  ggplot(aes(x = CALL_VOLUME, y = CALL_TIME_MEAN, label = SEGMENT)) +
  geom_point(aes(size = FTE), colour = "#0077C8") +
  geom_label_repel(aes(label = SEGMENT),
    box.padding = unit(0.35, "lines"),
    point.padding = unit(0.5, "lines"),
    segment.color = "#0077C8",
    force = 50,
    fontface = "bold",
    color = "white",
    fill = "#0077C8",
    size = 4
  ) +
  # facet_grid(.~YEAR) +
  coord_cartesian(ylim = c(300, 450), xlim = c(500, 8000)) +
  labs(
    x = "Calls per Month",
    y = "Call Time (Sec)",
    title = "Which Calls Consume Most Resources",
    subtitle = "Top 10 Contact Reasons with Highest FTE Need",
    caption = "Measurement period: Jan-May, 2019"
  ) +
  theme(
    plot.title = element_text(color = "#0077C8", face = "bold"),
    plot.subtitle = element_text(color = "#0077C8"),
    plot.caption = element_text(color = "#0077C8"),
    axis.title.x = element_text(color = "#0077C8"),
    axis.title.y = element_text(color = "#0077C8"),
    axis.text.x = element_text(color = "#0077C8"),
    axis.text.y = element_text(color = "#0077C8"),
    legend.title = element_text(color = "#0077C8"),
    legend.text = element_text(color = "#0077C8")
  )
```





## 3.2. Wrap-Up Analysis

Total FTE can be broken down to  

* speak-time FTE
* wrap-up FTE

> In 2019 31% of FTE is spent on wrap-ups. That is a 10% increase compared to 2018

```{r}
t_call_times %>%
  # Transform data
  filter(PRODUCT_LINE != "UNKNOWN") %>% 
  filter(
    (EVENT_END >= as.Date('2018-01-01') & EVENT_END < as.Date('2018-06-01')) |
    (EVENT_END >= as.Date('2019-01-01') & EVENT_END < as.Date('2019-06-01'))
         ) %>%
  mutate(YEAR = lubridate::year(EVENT_END)) %>% 
  mutate(EVENT_MONTH = floor_date(EVENT_END, unit = "month")) %>%
  group_by(YEAR, EVENT_MONTH) %>%
  summarize(
        CALL_VOLUME = n(),
        CALL_TIME_SEC = sum(CALL_TIME),
        SPEAK_TIME_SEC = sum(SPEAK_TIME),
        WRAPUP_TIME_SEC = sum(WRAPUP_TIME)) %>%
  ungroup() %>%
  left_join(t_mnap, by = c("EVENT_MONTH" = "IDOSZAK")) %>% 
  mutate(
    FTE = CALL_TIME_SEC/60/60/6.5/MNAP,
    COST = FTE/CALL_VOLUME*1000,
    SPEAK_FTE = SPEAK_TIME_SEC/60/60/6.5/MNAP,
    SPEAK_COST = SPEAK_FTE/CALL_VOLUME*1000,
    WRAPUP_FTE = WRAPUP_TIME_SEC/60/60/6.5/MNAP,
    WRAPUP_COST = WRAPUP_FTE/CALL_VOLUME*1000) %>%
  # Compute monthly averages
  group_by(YEAR) %>% 
  summarize(
            CALL_VOLUME = mean(CALL_VOLUME),
            FTE = mean(FTE),
            COST = mean(COST),
            SPEAK_FTE = mean(SPEAK_FTE),
            SPEAK_COST = mean(SPEAK_COST),
            WRAPUP_FTE = mean(WRAPUP_FTE),
            WRAPUP_COST = mean(WRAPUP_COST)) %>% 
  ungroup() %>% 
  mutate(WRAPUP_RATIO = WRAPUP_FTE/FTE) %>% 
  # Plot
  ggplot(aes(x = as.character(YEAR), y = WRAPUP_RATIO)) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = paste(round(WRAPUP_RATIO*100, 1), "%")), vjust = -0.1) +
    scale_y_continuous(label = percent) +
    #facet_grid(YEAR~.) +
    labs(
      x = "Year",
    y = "Ratio of Wrap-up FTE to Total FTE",
    title = "Proprotion of FTE Spent on Wrap-up"
    )
```

### 3.2.1. Wrap-Up FTE Ratio by Contact Type

```{r, include=FALSE}
t_call_times %>%
  # Transform data
  filter(PRODUCT_LINE != "UNKNOWN") %>% 
  filter(
    (EVENT_END >= as.Date('2018-01-01') & EVENT_END < as.Date('2018-06-01')) |
    (EVENT_END >= as.Date('2019-01-01') & EVENT_END < as.Date('2019-06-01'))
         ) %>%
  mutate(YEAR = forcats::fct_rev(factor(as.character(lubridate::year(EVENT_END))))) %>%
  mutate(EVENT_MONTH = floor_date(EVENT_END, unit = "month"),
         #CASE_TYPE_EN = forcats::fct_lump(factor(CASE_TYPE_EN), n = 7),
         SEGMENT = forcats::fct_lump(paste(CASE_TYPE_EN, PRODUCT_LINE), n = 9, other_level = "Everything else")) %>%
  group_by(YEAR, EVENT_MONTH,  SEGMENT) %>%
  summarize(
        CALL_VOLUME = n(),
        CALL_TIME_SEC = sum(CALL_TIME),
        SPEAK_TIME_SEC = sum(SPEAK_TIME),
        WRAPUP_TIME_SEC = sum(WRAPUP_TIME)) %>%
  ungroup() %>%
  left_join(t_mnap, by = c("EVENT_MONTH" = "IDOSZAK")) %>% 
  mutate(
    FTE = CALL_TIME_SEC/60/60/6.5/MNAP,
    COST = FTE/CALL_VOLUME*1000,
    SPEAK_FTE = SPEAK_TIME_SEC/60/60/6.5/MNAP,
    SPEAK_COST = SPEAK_FTE/CALL_VOLUME*1000,
    WRAPUP_FTE = WRAPUP_TIME_SEC/60/60/6.5/MNAP,
    WRAPUP_COST = WRAPUP_FTE/CALL_VOLUME*1000) %>%
  # Compute monthly averages
  group_by(YEAR, SEGMENT) %>% 
  summarize(
            CALL_VOLUME = mean(CALL_VOLUME),
            FTE = mean(FTE),
            COST = mean(COST),
            SPEAK_FTE = mean(SPEAK_FTE),
            SPEAK_COST = mean(SPEAK_COST),
            WRAPUP_FTE = mean(WRAPUP_FTE),
            WRAPUP_COST = mean(WRAPUP_COST)) %>% 
  ungroup() %>% 
  mutate(WRAPUP_RATIO = WRAPUP_FTE/FTE) %>% 
  mutate(SEGMENT = forcats::fct_reorder(SEGMENT, WRAPUP_RATIO, sum)) %>% 
  mutate(SEGMENT = forcats::fct_relevel(SEGMENT, "Everything else")) %>% 
  filter(SEGMENT != "Everything else") %>% 
  # Plot
  ggplot(aes(x = SEGMENT, y = WRAPUP_RATIO, fill = YEAR)) +
    geom_bar(stat = "identity", position=position_dodge()) +
    geom_text(aes(label = paste(round(WRAPUP_RATIO*100, 1), "%")), position = position_dodge(width = 1), size = 3, colour = "#0077C8", hjust = -0.1) +
    scale_y_continuous(label = percent) +
    guides(fill = guide_legend(reverse = TRUE)) +
    coord_flip(ylim = c(0, 0.32)) +
    scale_fill_brewer(palette = "Paired") +
  labs(
    x = "Contact Type",
    y = "Ratio of Wrap-up FTE to Total FTE",
    title = "Resources Spent on Call Administration",
    subtitle = "Proprotion of FTE Spent on Wrap-up",
    caption = "Measurement period: Jan-May, 2019"
  ) +
  theme(
    plot.title = element_text(color = "#0077C8", face = "bold"),
    plot.subtitle = element_text(color = "#0077C8"),
    plot.caption = element_text(color = "#0077C8"),
    axis.title.x = element_text(color = "#0077C8"),
    axis.title.y = element_text(color = "#0077C8"),
    axis.text.x = element_text(color = "#0077C8"),
    axis.text.y = element_text(color = "#0077C8"),
    legend.title = element_text(color = "#0077C8"),
    legend.text = element_text(color = "#0077C8")
  )
```


```{r, fig.height=6.5, fig.width=8}
t_call_times %>%
  # Transform data
  filter(PRODUCT_LINE != "UNKNOWN") %>%
  filter(EVENT_END >= as.Date("2019-01-01") & EVENT_END < as.Date("2019-06-01")) %>%
  mutate(YEAR = forcats::fct_rev(factor(as.character(lubridate::year(EVENT_END))))) %>%
  mutate(
    EVENT_MONTH = floor_date(EVENT_END, unit = "month"),
    # CASE_TYPE_EN = forcats::fct_lump(factor(CASE_TYPE_EN), n = 7),
    SEGMENT = forcats::fct_lump(paste(CASE_TYPE_EN, PRODUCT_LINE), n = 10, other_level = "Everything else")
  ) %>%
  group_by(YEAR, EVENT_MONTH, SEGMENT) %>%
  summarize(
    CALL_VOLUME = n(),
    CALL_TIME_SEC = sum(CALL_TIME),
    SPEAK_TIME_SEC = sum(SPEAK_TIME),
    WRAPUP_TIME_SEC = sum(WRAPUP_TIME)
  ) %>%
  ungroup() %>%
  left_join(t_mnap, by = c("EVENT_MONTH" = "IDOSZAK")) %>%
  mutate(
    FTE = CALL_TIME_SEC / 60 / 60 / 6.5 / MNAP,
    COST = FTE / CALL_VOLUME * 1000,
    SPEAK_FTE = SPEAK_TIME_SEC / 60 / 60 / 6.5 / MNAP,
    SPEAK_COST = SPEAK_FTE / CALL_VOLUME * 1000,
    WRAPUP_FTE = WRAPUP_TIME_SEC / 60 / 60 / 6.5 / MNAP,
    WRAPUP_COST = WRAPUP_FTE / CALL_VOLUME * 1000
  ) %>%
  # Compute monthly averages
  group_by(YEAR, SEGMENT) %>%
  summarize(
    CALL_VOLUME = mean(CALL_VOLUME),
    FTE = mean(FTE),
    COST = mean(COST),
    SPEAK_FTE = mean(SPEAK_FTE),
    SPEAK_COST = mean(SPEAK_COST),
    WRAPUP_FTE = mean(WRAPUP_FTE),
    WRAPUP_COST = mean(WRAPUP_COST)
  ) %>%
  ungroup() %>%
  mutate(WRAPUP_RATIO = WRAPUP_FTE / FTE) %>%
  mutate(SEGMENT = forcats::fct_reorder(SEGMENT, WRAPUP_RATIO, sum)) %>%
  mutate(SEGMENT = forcats::fct_relevel(SEGMENT, "Everything else")) %>%
  filter(SEGMENT != "Everything else") %>%
  # Plot
  ggplot(aes(x = SEGMENT, y = WRAPUP_RATIO)) +
  geom_bar(stat = "identity", position = position_dodge(), colour = "#0077C8", fill = "#0077C8") +
  geom_text(aes(label = paste(round(WRAPUP_RATIO * 100, 1), "%")), position = position_dodge(width = 1), size = 3, colour = "#0077C8", hjust = -0.1) +
  geom_hline(aes(yintercept = 0.186), colour="#BB0000", linetype="dashed", size = 1) +
  scale_y_continuous(label = percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  coord_flip(ylim = c(0, 0.3)) +
  # scale_fill_brewer(palette = "Paired") +
  labs(
    x = "Contact Reason",
    y = "Wrap-up/Total FTE",
    title = "Resources Spent on Call Administration",
    subtitle = "Proprotion of FTE Spent on Wrap-up across Contact Reasons",
    caption = "Measurement period: Jan-May, 2019"
  ) +
  theme(
    plot.title = element_text(color = "#0077C8", face = "bold"),
    plot.subtitle = element_text(color = "#0077C8"),
    plot.caption = element_text(color = "#0077C8"),
    axis.title.x = element_text(color = "#0077C8"),
    axis.title.y = element_text(color = "#0077C8"),
    axis.text.x = element_text(color = "#0077C8"),
    axis.text.y = element_text(color = "#0077C8"),
    legend.title = element_text(color = "#0077C8"),
    legend.text = element_text(color = "#0077C8")
  )
```

# 4. Concentration


```{r, include = TRUE, fig.width=10}
t_call_times %>%
  # Transform data
  filter(PRODUCT_LINE != "UNKNOWN") %>% 
  filter(
    EVENT_END >= as.Date('2019-01-01') & EVENT_END < as.Date('2019-06-01')
         ) %>%
  mutate(YEAR = paste("Jan-May", lubridate::year(EVENT_END))) %>% 
  mutate(EVENT_MONTH = floor_date(EVENT_END, unit = "month"),
         #CASE_TYPE_EN = forcats::fct_lump(factor(CASE_TYPE_EN), n = 7),
         SEGMENT = forcats::fct_lump(CASE_TYPE_EN, n = 9, other_level = "Everything else")) %>%
  group_by(YEAR, EVENT_MONTH,  SEGMENT) %>%
  summarize(CALL_VOLUME = n(),
            CALL_TIME_SEC = sum(CALL_TIME)) %>%
  ungroup() %>%
  left_join(t_mnap, by = c("EVENT_MONTH" = "IDOSZAK")) %>% 
  mutate(FTE = CALL_TIME_SEC/60/60/6.5/MNAP,
         COST = FTE/CALL_VOLUME*1000) %>%
  # Compute monthly averages
  group_by(YEAR, SEGMENT) %>% 
  summarize(
            CALL_VOLUME = mean(CALL_VOLUME),
            FTE = mean(FTE),
            COST = mean(COST)) %>%
  #filter(SEGMENT != "Everything else") %>% 
  arrange(YEAR, desc(FTE)) %>% 
  # Plot
  ggplot(aes(x = CALL_VOLUME, y = COST, label = SEGMENT)) +
    geom_point(aes(size = FTE), colour = "blue") +
    geom_label_repel(aes(label = SEGMENT),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50',
                  force = 50,
                  size = 3.5) +
    facet_grid(.~YEAR) +
    coord_cartesian(ylim = c(0.6, 1)) +
    labs(
      x = "Calls (Monthly Average)",
    y = "Cost per Call (Normalized FTE)",
    title = "Impact Map of Processes"
    )
```